#ifndef _P4A_IOMUX_H
#define _P4A_IOMUX_H

enum P4A_IOMUX_MODE {
	IOMUX_MODE_0 = 0,
	IOMUX_MODE_1,
	IOMUX_MODE_2,
	IOMUX_MODE_3,
	IOMUX_MODE_4,
	IOMUX_MODE_MAX,
};

#define MUX_VALUE(regid, shift, fn)		((regid)<<16 | (shift)<<8 | (fn))


/* SPI_CLK_PAD */
#define SPICLK_PAD_MODE(i)				MUX_VALUE(1, 0, (i))
#define MP_SPICLK_PAD_SPIS_CLK			SPICLK_PAD_MODE(IOMUX_MODE_0)
#define MP_SPICLK_PAD_SPIM2_CLK			SPICLK_PAD_MODE(IOMUX_MODE_1)
#define MP_SPICLK_PAD_A2B_DAT27			SPICLK_PAD_MODE(IOMUX_MODE_2)
#define MP_SPICLK_PAD_TESTPIN1			SPICLK_PAD_MODE(IOMUX_MODE_3)
#define MP_SPICLK_PAD_GPIO28			SPICLK_PAD_MODE(IOMUX_MODE_4)

/* SPI_CS_PAD */
#define SPICS_PAD_MODE(i)				MUX_VALUE(1, 4, (i))
#define MP_SPICS_PAD_SPIS_CS			SPICS_PAD_MODE(IOMUX_MODE_0)
#define MP_SPICS_PAD_SPIM2_CS			SPICS_PAD_MODE(IOMUX_MODE_1)
#define MP_SPICS_PAD_A2B_DAT26			SPICS_PAD_MODE(IOMUX_MODE_2)
#define MP_SPICS_PAD_TESTPIN0			SPICS_PAD_MODE(IOMUX_MODE_3)
#define MP_SPICS_PAD_GPIO27				SPICS_PAD_MODE(IOMUX_MODE_4)

/* SPI_DI_PAD */
#define SPIDI_PAD_MODE(i)				MUX_VALUE(1, 8, (i))
#define MP_SPIDI_PAD_SPIS_MOSI			SPIDI_PAD_MODE(IOMUX_MODE_0)
#define MP_SPIDI_PAD_SPIM2_MISO			SPIDI_PAD_MODE(IOMUX_MODE_1)
#define MP_SPIDI_PAD_A2B_DAT28			SPIDI_PAD_MODE(IOMUX_MODE_2)
#define MP_SPIDI_PAD_TESTPIN2			SPIDI_PAD_MODE(IOMUX_MODE_3)
#define MP_SPIDI_PAD_GPIO29				SPIDI_PAD_MODE(IOMUX_MODE_4)

/* SPI_DO_PAD */
#define SPIDO_PAD_MODE(i)				MUX_VALUE(1, 12, (i))
#define MP_SPIDO_PAD_SPIS_MISO			SPIDO_PAD_MODE(IOMUX_MODE_0)
#define MP_SPIDO_PAD_SPIM2_MOSI			SPIDO_PAD_MODE(IOMUX_MODE_1)
#define MP_SPIDO_PAD_TESTPING3			SPIDO_PAD_MODE(IOMUX_MODE_3)
#define MP_SPIDO_PAD_GPIO31				SPIDO_PAD_MODE(IOMUX_MODE_4)

/* UART2_TX_PAD */
#define UART2TX_PAD_MODE(i)				MUX_VALUE(1, 16, (i))
#define MP_UART2TX_PAD_UART3_CTS		UART2TX_PAD_MODE(IOMUX_MODE_0)
#define MP_UART2TX_PAD_UART2_TX			UART2TX_PAD_MODE(IOMUX_MODE_1)
#define MP_UART2TX_PAD_GPIO23			UART2TX_PAD_MODE(IOMUX_MODE_4)

/* UART2_RX_PAD */
#define UART2RX_PAD_MODE(i)				MUX_VALUE(1, 20, (i))
#define MP_UART2RX_PAD_UART3_RTS		UART2RX_PAD_MODE(IOMUX_MODE_0)
#define MP_UART2RX_PAD_UART2_RX			UART2RX_PAD_MODE(IOMUX_MODE_1)
#define MP_UART2RX_PAD_GPIO24			UART2RX_PAD_MODE(IOMUX_MODE_4)

/* UART3_RX_PAD */
#define UART3RX_PAD_MODE(i)				MUX_VALUE(1, 24, (i))
#define MP_UART3RX_PAD_UART3_RX			UART3RX_PAD_MODE(IOMUX_MODE_0)
#define MP_UART3RX_PAD_DRVVBUS2			UART3RX_PAD_MODE(IOMUX_MODE_1)
#define MP_UART3RX_PAD_GPIO26			UART3RX_PAD_MODE(IOMUX_MODE_4)


/* UART3_TX_PAD */
#define UART3TX_PAD_MODE(i)				MUX_VALUE(1, 28, (i))
#define MP_UART3TX_PAD_UART3_TX			UART3TX_PAD_MODE(IOMUX_MODE_0)
#define MP_UART3TX_PAD_DRVVBUS1			UART3TX_PAD_MODE(IOMUX_MODE_1)
#define MP_UART3TX_PAD_GPIO25			UART3TX_PAD_MODE(IOMUX_MODE_4)


/* ARM_RTCK_PAD */
#define ARMRTCK_PAD_MODE(i)				MUX_VALUE(2, 0, (i))
#define MP_ARMRTCK_PAD_ARM_RTCK			ARMRTCK_PAD_MODE(IOMUX_MODE_0)
#define MP_ARMRTCK_PAD_ARM2_RTCK		ARMRTCK_PAD_MODE(IOMUX_MODE_1)
#define MP_ARMRTCK_PAD_GPIO123			ARMRTCK_PAD_MODE(IOMUX_MODE_4)

/* ARM_TCK_PAD */
#define ARMTCK_PAD_MODE(i)				MUX_VALUE(2, 4, (i))
#define MP_ARMTCK_PAD_ARM_TCK			ARMTCK_PAD_MODE(IOMUX_MODE_0)
#define MP_ARMTCK_PAD_ARM2_TCK			ARMTCK_PAD_MODE(IOMUX_MODE_1)
#define MP_ARMTCK_PAD_DSP_TCK			ARMTCK_PAD_MODE(IOMUX_MODE_2)
#define MP_ARMTCK_PAD_GPIO124			ARMTCK_PAD_MODE(IOMUX_MODE_4)

/* ARM_TDI_PAD */
#define ARMTDI_PAD_MODE(i)				MUX_VALUE(2, 8, (i))
#define MP_ARMTDI_PAD_ARM_TDI			ARMTDI_PAD_MODE(IOMUX_MODE_0)
#define MP_ARMTDI_PAD_ARM2_TDI			ARMTDI_PAD_MODE(IOMUX_MODE_1)
#define MP_ARMTDI_PAD_DSP_TDI			ARMTDI_PAD_MODE(IOMUX_MODE_2)
#define MP_ARMTDI_PAD_GPIO125			ARMTDI_PAD_MODE(IOMUX_MODE_4)

/* ARM_TDO_PAD */
#define ARMTDO_PAD_MODE(i)				MUX_VALUE(2, 12, (i))
#define MP_ARMTDO_PAD_ARM_TDO			ARMTDO_PAD_MODE(IOMUX_MODE_0)
#define MP_ARMTDO_PAD_ARM2_TDO			ARMTDO_PAD_MODE(IOMUX_MODE_1)
#define MP_ARMTDO_PAD_DSP_TDO			ARMTDO_PAD_MODE(IOMUX_MODE_2)
#define MP_ARMTDO_PAD_GPIO126			ARMTDO_PAD_MODE(IOMUX_MODE_4)

/* ARM_TMS_PAD */
#define ARMTMS_PAD_MODE(i)				MUX_VALUE(2, 16, (i))
#define MP_ARMTMS_PAD_ARM_TMS			ARMTMS_PAD_MODE(IOMUX_MODE_0)
#define MP_ARMTMS_PAD_ARM2_TMS			ARMTMS_PAD_MODE(IOMUX_MODE_1)
#define MP_ARMTMS_PAD_DSP_TMS			ARMTMS_PAD_MODE(IOMUX_MODE_2)
#define MP_ARMTMS_PAD_GPIO127			ARMTMS_PAD_MODE(IOMUX_MODE_4)

/* ARM_TRSTN_PAD */
#define ARMTRSTN_PAD_MODE(i)			MUX_VALUE(2, 20, (i))
#define MP_ARMTRSTN_PAD_ARM_TRSTN		ARMTRSTN_PAD_MODE(IOMUX_MODE_0)
#define MP_ARMTRSTN_PAD_ARM2_TRSTN		ARMTRSTN_PAD_MODE(IOMUX_MODE_1)
#define MP_ARMTRSTN_PAD_DSP_TRSTN		ARMTRSTN_PAD_MODE(IOMUX_MODE_2)
#define MP_ARMTRSTN_PAD_GPIO128			ARMTRSTN_PAD_MODE(IOMUX_MODE_4)

/* EXT_WAKEUP_INT_PAD */
#define EXTWAKEUPINT_PAD_MODE(i)		MUX_VALUE(2, 24, (i))
#define MP_EXTWAKEUPINT_PAD_EXTWAKEUP_INT	EXTWAKEUPINT_PAD_MODE(IOMUX_MODE_0)
#define MP_EXTWAKEUPINT_PAD_TESTPIN6		EXTWAKEUPINT_PAD_MODE(IOMUX_MODE_3)
#define MP_EXTWAKEUPINT_PAD_GPIO11			EXTWAKEUPINT_PAD_MODE(IOMUX_MODE_4)

/* GPIO10_PAD */
#define GPIO10_PAD_MODE(i)				MUX_VALUE(2, 28, (i))
#define MP_GPIO10_PAD_SLEEP_32K768		GPIO10_PAD_MODE(IOMUX_MODE_0)
#define MP_GPIO10_PAD_A2B_DAT39			GPIO10_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO10_PAD_TESTPIN5			GPIO10_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO10_PAD_GPIO10			GPIO10_PAD_MODE(IOMUX_MODE_4)

/* BOOT_SEL0_PAD */
#define BOOTSEL0_PAD_MODE(i)			MUX_VALUE(3, 0, (i))
#define MP_BOOTSEL0_PAD_BOOT_SEL0		BOOTSEL0_PAD_MODE(IOMUX_MODE_0)
#define MP_BOOTSEL0_PAD_GPIO119			BOOTSEL0_PAD_MODE(IOMUX_MODE_4)

/* BOOT_SEL1_PAD */
#define BOOTSEL1_PAD_MODE(i)			MUX_VALUE(3, 4, (i))
#define MP_BOOTSEL1_PAD_BOOT_SEL1		BOOTSEL1_PAD_MODE(IOMUX_MODE_0)
#define MP_BOOTSEL1_PAD_GPIO120			BOOTSEL1_PAD_MODE(IOMUX_MODE_4)

/* BOOT_SEL2_PAD */
#define BOOTSEL2_PAD_MODE(i)			MUX_VALUE(3, 8, (i))
#define MP_BOOTSEL2_PAD_BOOT_SEL2		BOOTSEL2_PAD_MODE(IOMUX_MODE_0)
#define MP_BOOTSEL2_PAD_GPIO121			BOOTSEL2_PAD_MODE(IOMUX_MODE_4)

/* BOOT_SEL3_PAD */
#define BOOTSEL3_PAD_MODE(i)			MUX_VALUE(3, 12, (i))
#define MP_BOOTSEL3_PAD_BOOT_SEL3		BOOTSEL3_PAD_MODE(IOMUX_MODE_0)
#define MP_BOOTSEL3_PAD_GPIO122			BOOTSEL3_PAD_MODE(IOMUX_MODE_4)
#define MP_BOOTSEL1_PAD_BOOT_SEL1		BOOTSEL1_PAD_MODE(IOMUX_MODE_0)
#define MP_BOOTSEL1_PAD_GPIO120			BOOTSEL1_PAD_MODE(IOMUX_MODE_4)

/* GPIO0_PAD */
#define GPIO0_PAD_MODE(i)				MUX_VALUE(3, 16, (i))
#define MP_GPIO0_PAD_UART1_TX			GPIO0_PAD_MODE(IOMUX_MODE_0)
#define MP_GPIO0_PAD_A2B_DAT29			GPIO0_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO0_PAD_TA_STROBE53		GPIO0_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO0_PAD_GPIO0				GPIO0_PAD_MODE(IOMUX_MODE_4)

/* GPIO1_PAD */
#define GPIO1_PAD_MODE(i)				MUX_VALUE(3, 20, (i))
#define MP_GPIO1_PAD_UART1_RX			GPIO1_PAD_MODE(IOMUX_MODE_0)
#define MP_GPIO1_PAD_A2B_DAT30			GPIO1_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO1_PAD_TA_STROBE54		GPIO1_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO1_PAD_GPIO1				GPIO1_PAD_MODE(IOMUX_MODE_4)

/* GPIO2_PAD */
#define GPIO2_PAD_MODE(i)				MUX_VALUE(3, 24, (i))
#define MP_GPIO2_PAD_A2B_DAT31			GPIO2_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO2_PAD_TA_STROBE55		GPIO2_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO2_PAD_GPIO2				GPIO2_PAD_MODE(IOMUX_MODE_4)

/* GPIO3_PAD */
#define GPIO3_PAD_MODE(i)				MUX_VALUE(3, 28, (i))
#define MP_GPIO3_PAD_A2B_DAT32			GPIO3_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO3_PAD_TA_STROBE56		GPIO3_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO3_PAD_GPIO3				GPIO3_PAD_MODE(IOMUX_MODE_4)


/* GPIO4_PAD */
#define GPIO4_PAD_MODE(i)				MUX_VALUE(4, 0, (i))
#define MP_GPIO4_PAD_A2B_DAT33			GPIO4_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO4_PAD_TA_STROBE57		GPIO4_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO4_PAD_GPIO4				GPIO4_PAD_MODE(IOMUX_MODE_4)

/* GPIO5_PAD */
#define GPIO5_PAD_MODE(i)				MUX_VALUE(4, 4, (i))
#define MP_GPIO5_PAD_A2B_DAT34			GPIO5_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO5_PAD_TA_STROBE58		GPIO5_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO5_PAD_GPIO5				GPIO5_PAD_MODE(IOMUX_MODE_4)

/* GPIO6_PAD */
#define GPIO6_PAD_MODE(i)				MUX_VALUE(4, 8, (i))
#define MP_GPIO6_PAD_A2B_DAT35			GPIO6_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO6_PAD_TA_STROBE59		GPIO6_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO6_PAD_GPIO6				GPIO6_PAD_MODE(IOMUX_MODE_4)

/* GPIO7_PAD */
#define GPIO7_PAD_MODE(i)				MUX_VALUE(4, 12, (i))
#define MP_GPIO7_PAD_SDM_CARDDETECT		GPIO7_PAD_MODE(IOMUX_MODE_0)
#define MP_GPIO7_PAD_A2B_DAT36			GPIO7_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO7_PAD_TA_STROBE60		GPIO7_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO7_PAD_GPIO7				GPIO7_PAD_MODE(IOMUX_MODE_4)

/* GPIO8_PAD */
#define GPIO8_PAD_MODE(i)				MUX_VALUE(4, 16, (i))
#define MP_GPIO8_PAD_SDM_WPROTECT		GPIO8_PAD_MODE(IOMUX_MODE_0)
#define MP_GPIO8_PAD_A2B_DAT37			GPIO8_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO8_PAD_TA_STROBE61		GPIO8_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO8_PAD_GPIO8				GPIO8_PAD_MODE(IOMUX_MODE_4)

/* GPIO9_PAD */
#define GPIO9_PAD_MODE(i)				MUX_VALUE(4, 20, (i))
#define MP_GPIO9_PAD_A2B_DAT38			GPIO9_PAD_MODE(IOMUX_MODE_2)
#define MP_GPIO9_PAD_TESTPIN4			GPIO9_PAD_MODE(IOMUX_MODE_3)
#define MP_GPIO9_PAD_GPIO9				GPIO9_PAD_MODE(IOMUX_MODE_4)

/* I2C_SCL_PAD */
#define I2CSCL_PAD_MODE(i)				MUX_VALUE(4, 24, (i))
#define MP_I2CSCL_PAD_IICS_SCL			I2CSCL_PAD_MODE(IOMUX_MODE_0)
#define MP_I2CSCL_PAD_IICM1_SCL			I2CSCL_PAD_MODE(IOMUX_MODE_1)
#define MP_I2CSCL_PAD_GPIO129			I2CSCL_PAD_MODE(IOMUX_MODE_4)

/* I2C_SDA_PAD */
#define I2CSDA_PAD_MODE(i)				MUX_VALUE(4, 28, (i))
#define MP_I2CSDA_PAD_IICS_SDA			I2CSDA_PAD_MODE(IOMUX_MODE_0)
#define MP_I2CSDA_PAD_IICM1_SDA			I2CSDA_PAD_MODE(IOMUX_MODE_1)
#define MP_I2CSDA_PAD_GPIO130			I2CSDA_PAD_MODE(IOMUX_MODE_4)

/* JE1_D0_PAD */
#define JE1D0_PAD_MODE(i)				MUX_VALUE(5, 0, (i))
#define MP_JE1DO_PAD_ADC1_IQ01			JE1D0_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1DO_PAD_JE1_D00			JE1D0_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1DO_PAD_B2A_DAT15			JE1D0_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1DO_PAD_GPIO70				JE1D0_PAD_MODE(IOMUX_MODE_4)

/* JE1_D10_PAD */
#define JE1D10_PAD_MODE(i)				MUX_VALUE(5, 4, (i))
#define MP_JE1D1O_PAD_ADC1_IQ11			JE1D10_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D1O_PAD_JE1_D10			JE1D10_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D1O_PAD_B2A_DAT25			JE1D10_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D1O_PAD_GPIO80			JE1D10_PAD_MODE(IOMUX_MODE_4)

/* JE1_D11_PAD */
#define JE1D11_PAD_MODE(i)				MUX_VALUE(5, 8, (i))
#define MP_JE1D11_PAD_DAC_CLK			JE1D11_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D11_PAD_JE1_D11			JE1D11_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D11_PAD_B2A_DAT26			JE1D11_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D11_PAD_GPIO81			JE1D11_PAD_MODE(IOMUX_MODE_4)

/* JE1_D1_PAD */
#define JE1D1_PAD_MODE(i)				MUX_VALUE(5, 12, (i))
#define MP_JE1D1_PAD_ADC1_IQ02			JE1D1_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D1_PAD_JE1_D01			JE1D1_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D1_PAD_B2A_DAT16			JE1D1_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D1_PAD_GPIO71				JE1D1_PAD_MODE(IOMUX_MODE_4)

/* JE1_D2_PAD */
#define JE1D2_PAD_MODE(i)				MUX_VALUE(5, 16, (i))
#define MP_JE1D2_PAD_ADC1_IQ03			JE1D2_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D2_PAD_JE1_D02			JE1D2_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D2_PAD_B2A_DAT17			JE1D2_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D2_PAD_GPIO72				JE1D2_PAD_MODE(IOMUX_MODE_4)

/* JE1_D3_PAD */
#define JE1D3_PAD_MODE(i)				MUX_VALUE(5, 20, (i))
#define MP_JE1D3_PAD_ADC1_IQ04			JE1D3_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D3_PAD_JE1_D03			JE1D3_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D3_PAD_B2A_DAT18			JE1D3_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D3_PAD_GPIO73				JE1D3_PAD_MODE(IOMUX_MODE_4)

/* JE1_D4_PAD */
#define JE1D4_PAD_MODE(i)				MUX_VALUE(5, 24, (i))
#define MP_JE1D4_PAD_ADC1_IQ05			JE1D4_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D4_PAD_JE1_D04			JE1D4_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D4_PAD_B2A_DAT19			JE1D4_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D4_PAD_GPIO74				JE1D4_PAD_MODE(IOMUX_MODE_4)

/* JE1_D5_PAD */
#define JE1D5_PAD_MODE(i)				MUX_VALUE(5, 28, (i))
#define MP_JE1D5_PAD_ADC1_IQ06			JE1D5_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D5_PAD_JE1_D05			JE1D5_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D5_PAD_B2A_DAT20			JE1D5_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D5_PAD_GPIO75				JE1D5_PAD_MODE(IOMUX_MODE_4)

/* JE1_D6_PAD */
#define JE1D6_PAD_MODE(i)				MUX_VALUE(6, 0, (i))
#define MP_JE1D6_PAD_ADC1_IQ07			JE1D6_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D6_PAD_JE1_D06			JE1D6_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D6_PAD_B2A_DAT21			JE1D6_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D6_PAD_GPIO76				JE1D6_PAD_MODE(IOMUX_MODE_4)

/* JE1_D7_PAD */
#define JE1D7_PAD_MODE(i)				MUX_VALUE(6, 4, (i))
#define MP_JE1D7_PAD_ADC1_IQ08			JE1D7_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D7_PAD_JE1_D07			JE1D7_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D7_PAD_B2A_DAT22			JE1D7_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D7_PAD_GPIO77				JE1D7_PAD_MODE(IOMUX_MODE_4)

/* JE1_D8_PAD */
#define JE1D8_PAD_MODE(i)				MUX_VALUE(6, 8, (i))
#define MP_JE1D8_PAD_ADC1_IQ09			JE1D8_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D8_PAD_JE1_D08			JE1D8_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D8_PAD_B2A_DAT23			JE1D8_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D8_PAD_GPIO78				JE1D8_PAD_MODE(IOMUX_MODE_4)

/* JE1_D9_PAD */
#define JE1D9_PAD_MODE(i)				MUX_VALUE(6, 12, (i))
#define MP_JE1D9_PAD_ADC1_IQ10			JE1D9_PAD_MODE(IOMUX_MODE_0)
#define MP_JE1D9_PAD_JE1_D09			JE1D9_PAD_MODE(IOMUX_MODE_1)
#define MP_JE1D9_PAD_B2A_DAT24			JE1D9_PAD_MODE(IOMUX_MODE_2)
#define MP_JE1D9_PAD_GPIO79				JE1D9_PAD_MODE(IOMUX_MODE_4)

/* JE2_D0_PAD */
#define JE2D0_PAD_MODE(i)				MUX_VALUE(6, 16, (i))
#define MP_JE2D0_PAD_ADC2_IQ00			JE2D0_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D0_PAD_JE2_D00			JE2D0_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D0_PAD_B2A_WLD			JE2D0_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D0_PAD_TA_STREOBE37		JE2D0_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D0_PAD_GPIO83				JE2D0_PAD_MODE(IOMUX_MODE_4)

/* JE2_D10_PAD */
#define JE2D10_PAD_MODE(i)				MUX_VALUE(6, 20, (i))
#define MP_JE2D10_PAD_ADC2_IQ10			JE2D10_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D10_PAD_JE2_D10			JE2D10_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D10_PAD_B2A_DAT36			JE2D10_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D10_PAD_TA_STREOBE47		JE2D10_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D10_PAD_GPIO93			JE2D10_PAD_MODE(IOMUX_MODE_4)

/* JE2_D11_PAD */
#define JE2D11_PAD_MODE(i)				MUX_VALUE(6, 24, (i))
#define MP_JE2D11_PAD_ADC2_IQ11			JE2D11_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D11_PAD_JE2_D11			JE2D11_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D11_PAD_B2A_DAT37			JE2D11_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D11_PAD_TA_STREOBE48		JE2D11_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D11_PAD_GPIO94			JE2D11_PAD_MODE(IOMUX_MODE_4)

/* JE2_D1_PAD */
#define JE2D1_PAD_MODE(i)				MUX_VALUE(6, 28, (i))
#define MP_JE2D1_PAD_ADC2_IQ01			JE2D1_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D1_PAD_JE2_D01			JE2D1_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D1_PAD_B2A_DAT27			JE2D1_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D1_PAD_TA_STREOBE38		JE2D1_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D1_PAD_GPIO84				JE2D1_PAD_MODE(IOMUX_MODE_4)

/* JE2_D2_PAD */
#define JE2D2_PAD_MODE(i)				MUX_VALUE(7, 0, (i))
#define MP_JE2D2_PAD_ADC2_IQ02			JE2D2_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D2_PAD_JE2_D02			JE2D2_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D2_PAD_B2A_DAT28			JE2D2_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D2_PAD_TA_STREOBE39		JE2D2_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D2_PAD_GPIO85				JE2D2_PAD_MODE(IOMUX_MODE_4)

/* JE2_D3_PAD */
#define JE2D3_PAD_MODE(i)				MUX_VALUE(7, 4, (i))
#define MP_JE2D3_PAD_ADC2_IQ03			JE2D3_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D3_PAD_JE2_D03			JE2D3_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D3_PAD_B2A_DAT29			JE2D3_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D3_PAD_TA_STREOBE40		JE2D3_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D3_PAD_GPIO86				JE2D3_PAD_MODE(IOMUX_MODE_4)

/* JE2_D4_PAD */
#define JE2D4_PAD_MODE(i)				MUX_VALUE(7, 8, (i))
#define MP_JE2D4_PAD_ADC2_IQ04			JE2D4_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D4_PAD_JE2_D04			JE2D4_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D4_PAD_B2A_DAT30			JE2D4_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D4_PAD_TA_STREOBE41		JE2D4_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D4_PAD_GPIO87				JE2D4_PAD_MODE(IOMUX_MODE_4)

/* JE2_D5_PAD */
#define JE2D5_PAD_MODE(i)				MUX_VALUE(7, 12, (i))
#define MP_JE2D5_PAD_ADC2_IQ05			JE2D5_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D5_PAD_JE2_D05			JE2D5_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D5_PAD_B2A_DAT31			JE2D5_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D5_PAD_TA_STREOBE42		JE2D5_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D5_PAD_GPIO88				JE2D5_PAD_MODE(IOMUX_MODE_4)

/* JE2_D6_PAD */
#define JE2D6_PAD_MODE(i)				MUX_VALUE(7, 16, (i))
#define MP_JE2D6_PAD_ADC2_IQ06			JE2D6_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D6_PAD_JE2_D06			JE2D6_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D6_PAD_B2A_DAT32			JE2D6_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D6_PAD_TA_STREOBE43		JE2D6_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D6_PAD_GPIO89				JE2D6_PAD_MODE(IOMUX_MODE_4)

/* JE2_D7_PAD */
#define JE2D7_PAD_MODE(i)				MUX_VALUE(7, 20, (i))
#define MP_JE2D7_PAD_ADC2_IQ07			JE2D7_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D7_PAD_JE2_D07			JE2D7_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D7_PAD_B2A_DAT33			JE2D7_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D7_PAD_TA_STREOBE44		JE2D7_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D7_PAD_GPIO90				JE2D7_PAD_MODE(IOMUX_MODE_4)

/* JE2_D8_PAD */
#define JE2D8_PAD_MODE(i)				MUX_VALUE(7, 24, (i))
#define MP_JE2D8_PAD_ADC2_IQ08			JE2D8_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D8_PAD_JE2_D08			JE2D8_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D8_PAD_B2A_DAT34			JE2D8_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D8_PAD_TA_STREOBE45		JE2D8_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D8_PAD_GPIO91				JE2D8_PAD_MODE(IOMUX_MODE_4)

/* JE2_D9_PAD */
#define JE2D9_PAD_MODE(i)				MUX_VALUE(7, 28, (i))
#define MP_JE2D9_PAD_ADC2_IQ09			JE2D9_PAD_MODE(IOMUX_MODE_0)
#define MP_JE2D9_PAD_JE2_D09			JE2D9_PAD_MODE(IOMUX_MODE_1)
#define MP_JE2D9_PAD_B2A_DAT35			JE2D9_PAD_MODE(IOMUX_MODE_2)
#define MP_JE2D9_PAD_TA_STREOBE46		JE2D9_PAD_MODE(IOMUX_MODE_3)
#define MP_JE2D9_PAD_GPIO92				JE2D9_PAD_MODE(IOMUX_MODE_4)

/* JE_ENABLE_PAD */
#define JEENABLE_PAD_MODE(i)			MUX_VALUE(8, 0, (i))
#define MP_JEENABLE_PAD_ADC1_IQ00		JEENABLE_PAD_MODE(IOMUX_MODE_0)
#define MP_JEENABLE_PAD_JE_ENABLE		JEENABLE_PAD_MODE(IOMUX_MODE_1)
#define MP_JEENABLE_PAD_B2A_DAT14		JEENABLE_PAD_MODE(IOMUX_MODE_2)
#define MP_JEENABLE_PAD_TA_STROBE36		JEENABLE_PAD_MODE(IOMUX_MODE_3)
#define MP_JEENABLE_PAD_GPIO68			JEENABLE_PAD_MODE(IOMUX_MODE_4)

/* JE_RXFRAM_PAD */
#define JERXFRAM_PAD_MODE(i)			MUX_VALUE(8, 4, (i))
#define MP_JERXFRAM_PAD_ADC_CLK			JERXFRAM_PAD_MODE(IOMUX_MODE_0)
#define MP_JERXFRAM_PAD_JE_RXFRAM		JERXFRAM_PAD_MODE(IOMUX_MODE_1)
#define MP_JERXFRAM_PAD_B2A_DAT12		JERXFRAM_PAD_MODE(IOMUX_MODE_2)
#define MP_JERXFRAM_PAD_TA_STROBE34		JERXFRAM_PAD_MODE(IOMUX_MODE_3)
#define MP_JERXFRAM_PAD_GPIO66			JERXFRAM_PAD_MODE(IOMUX_MODE_4)

/* JE_TXNRX_PAD */
#define JETXNRX_PAD_MODE(i)				MUX_VALUE(8, 8, (i))
#define MP_JETXNRX_PAD_ADC1_DCO			JETXNRX_PAD_MODE(IOMUX_MODE_0)
#define MP_JETXNRX_PAD_JE_TXNRX			JETXNRX_PAD_MODE(IOMUX_MODE_1)
#define MP_JETXNRX_PAD_B2A_DAT13		JETXNRX_PAD_MODE(IOMUX_MODE_2)
#define MP_JETXNRX_PAD_TA_STROBE35		JETXNRX_PAD_MODE(IOMUX_MODE_3)
#define MP_JETXNRX_PAD_GPIO67			JETXNRX_PAD_MODE(IOMUX_MODE_4)

/* JE_TXFRAM_PAD */
#define JETXFRAM_PAD_MODE(i)			MUX_VALUE(8, 12, (i))
#define MP_JETXFRAM_PAD_ADC2_DCO		JETXFRAM_PAD_MODE(IOMUX_MODE_0)
#define MP_JETXFRAM_PAD_JE_TXFRAM		JETXFRAM_PAD_MODE(IOMUX_MODE_1)
#define MP_JETXFRAM_PAD_B2A_DAT11		JETXFRAM_PAD_MODE(IOMUX_MODE_2)
#define MP_JETXFRAM_PAD_TA_STROBE33		JETXFRAM_PAD_MODE(IOMUX_MODE_3)
#define MP_JETXFRAM_PAD_GPIO65			JETXFRAM_PAD_MODE(IOMUX_MODE_4)

/* NFD0_PAD */
#define NFD0_PAD_MODE(i)				MUX_VALUE(8, 16, (i))
#define MP_NFD0_PAD_NF_D0				NFD0_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD0_PAD_A2B_DAT18			NFD0_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD0_PAD_GPIO111				NFD0_PAD_MODE(IOMUX_MODE_4)


/* NFD1_PAD */
#define NFD1_PAD_MODE(i)				MUX_VALUE(8, 20, (i))
#define MP_NFD1_PAD_NF_D1				NFD1_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD1_PAD_A2B_DAT19			NFD1_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD1_PAD_GPIO112				NFD1_PAD_MODE(IOMUX_MODE_4)

/* NFD2_PAD */
#define NFD2_PAD_MODE(i)				MUX_VALUE(8, 24, (i))
#define MP_NFD2_PAD_NF_D2				NFD2_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD2_PAD_A2B_DAT20			NFD2_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD2_PAD_GPIO113				NFD2_PAD_MODE(IOMUX_MODE_4)

/* NFD3_PAD */
#define NFD3_PAD_MODE(i)				MUX_VALUE(8, 28, (i))
#define MP_NFD3_PAD_NF_D3				NFD3_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD3_PAD_A2B_DAT21			NFD3_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD3_PAD_GPIO114				NFD3_PAD_MODE(IOMUX_MODE_4)

/* NFD4_PAD */
#define NFD4_PAD_MODE(i)				MUX_VALUE(9, 0, (i))
#define MP_NFD4_PAD_NF_D4				NFD4_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD4_PAD_A2B_DAT22			NFD4_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD4_PAD_GPIO115				NFD4_PAD_MODE(IOMUX_MODE_4)

/* NFD5_PAD */
#define NFD5_PAD_MODE(i)				MUX_VALUE(9, 4, (i))
#define MP_NFD5_PAD_NF_D5				NFD5_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD5_PAD_A2B_DAT23			NFD5_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD5_PAD_GPIO116				NFD5_PAD_MODE(IOMUX_MODE_4)

/* NFD6_PAD */
#define NFD6_PAD_MODE(i)				MUX_VALUE(9, 8, (i))
#define MP_NFD6_PAD_NF_D6				NFD6_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD6_PAD_A2B_DAT24			NFD6_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD6_PAD_GPIO117				NFD6_PAD_MODE(IOMUX_MODE_4)

/* NFD7_PAD */
#define NFD7_PAD_MODE(i)				MUX_VALUE(9, 12, (i))
#define MP_NFD7_PAD_NF_D7				NFD7_PAD_MODE(IOMUX_MODE_0)
#define MP_NFD7_PAD_A2B_DAT25			NFD7_PAD_MODE(IOMUX_MODE_2)
#define MP_NFD7_PAD_GPIO118				NFD7_PAD_MODE(IOMUX_MODE_4)

/* NFALE_PAD */
#define NFALE_PAD_MODE(i)				MUX_VALUE(9, 16, (i))
#define MP_NFALE_PAD_NF_ALE				NFALE_PAD_MODE(IOMUX_MODE_0)
#define MP_NFALE_PAD_SFLASH_MOSI		NFALE_PAD_MODE(IOMUX_MODE_1)
#define MP_NFALE_PAD_SPIM1_MOSI			NFALE_PAD_MODE(IOMUX_MODE_2)
#define MP_NFALE_PAD_GPIO108			NFALE_PAD_MODE(IOMUX_MODE_4)

/* NFCEN0_PAD */
#define NFCEN0_PAD_MODE(i)				MUX_VALUE(9, 20, (i))
#define MP_NFCEN0_PAD_NF_CEN0			NFCEN0_PAD_MODE(IOMUX_MODE_0)
#define MP_NFCEN0_PAD_SFLASH_CSN		NFCEN0_PAD_MODE(IOMUX_MODE_1)
#define MP_NFCEN0_PAD_SPIM1_CS			NFCEN0_PAD_MODE(IOMUX_MODE_2)
#define MP_NFCEN0_PAD_GPIO105			NFCEN0_PAD_MODE(IOMUX_MODE_4)

/* NFCLE_PAD */ 
#define NFCLE_PAD_MODE(i)				MUX_VALUE(9, 24, (i))
#define MP_NFCLE_PAD_NF_CLE				NFCLE_PAD_MODE(IOMUX_MODE_0)
#define MP_NFCLE_PAD_SFLASH_MISO		NFCLE_PAD_MODE(IOMUX_MODE_1)
#define MP_NFCLE_PAD_SPIM1_MISO			NFCLE_PAD_MODE(IOMUX_MODE_2)
#define MP_NFCLE_PAD_GPIO107			NFCLE_PAD_MODE(IOMUX_MODE_4)

/* NFRBN0_PAD */ 
#define NFRBN0_PAD_MODE(i)				MUX_VALUE(9, 28, (i))
#define MP_NFRBN0_PAD_NF_RBN0			NFRBN0_PAD_MODE(IOMUX_MODE_0)
#define MP_NFRBN0_PAD_SFLASH_SCK		NFRBN0_PAD_MODE(IOMUX_MODE_1)
#define MP_NFRBN0_PAD_SPIM1_CLK			NFRBN0_PAD_MODE(IOMUX_MODE_2)
#define MP_NFRBN0_PAD_GPIO106			NFRBN0_PAD_MODE(IOMUX_MODE_4)

/* NFRDN_PAD */
#define NFRDN_PAD_MODE(i)				MUX_VALUE(10, 0, (i))
#define MP_NFRDN_PAD_NF_RDN				NFRDN_PAD_MODE(IOMUX_MODE_0)
#define MP_NFRDN_PAD_GPIO110			NFRDN_PAD_MODE(IOMUX_MODE_4)

/* NFWRN_PAD */
#define NFWRN_PAD_MODE(i)				MUX_VALUE(10, 4, (i))
#define MP_NFWRN_PAD_NF_WRN				NFWRN_PAD_MODE(IOMUX_MODE_0)
#define MP_NFWRN_PAD_SFLASH_CS2N		NFWRN_PAD_MODE(IOMUX_MODE_1)
#define MP_NFWRN_PAD_SPIM1_CS2			NFWRN_PAD_MODE(IOMUX_MODE_2)
#define MP_NFWRN_PAD_GPIO109			NFWRN_PAD_MODE(IOMUX_MODE_4)


/* RFGPO0_PAD */
#define RFGPO0_PAD_MODE(i)				MUX_VALUE(10, 8, (i))
#define MP_RFGPO0_PAD_RF_SPI4_DIO		RFGPO0_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO0_PAD_A2B_CLK			RFGPO0_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO0_PAD_TA_STROBE0		RFGPO0_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO0_PAD_GPIO32			RFGPO0_PAD_MODE(IOMUX_MODE_4)

/* RFGPO10_PAD */
#define RFGPO10_PAD_MODE(i)				MUX_VALUE(10, 12, (i))
#define MP_RFGPO10_PAD_A2B_DAT08		RFGPO10_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO10_PAD_TA_STROBE10		RFGPO10_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO10_PAD_GPIO42			RFGPO10_PAD_MODE(IOMUX_MODE_4)

/* RFGPO11_PAD */
#define RFGPO11_PAD_MODE(i)				MUX_VALUE(10, 16, (i))
#define MP_RFGPO11_PAD_A2B_DAT09		RFGPO11_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO11_PAD_TA_STROBE11		RFGPO11_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO11_PAD_GPIO43			RFGPO11_PAD_MODE(IOMUX_MODE_4)

/* RFGPO12_PAD */
#define RFGPO12_PAD_MODE(i)				MUX_VALUE(10, 20, (i))
#define MP_RFGPO12_PAD_A2B_DAT10		RFGPO12_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO12_PAD_TA_STROBE12		RFGPO12_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO12_PAD_GPIO44			RFGPO12_PAD_MODE(IOMUX_MODE_4)

/* RFGPO13_PAD */
#define RFGPO13_PAD_MODE(i)				MUX_VALUE(10, 24, (i))
#define MP_RFGPO13_PAD_RF_SPI2_DIO		RFGPO13_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO13_PAD_A2B_DAT11		RFGPO13_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO13_PAD_TA_STROBE13		RFGPO13_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO13_PAD_GPIO45			RFGPO13_PAD_MODE(IOMUX_MODE_4)

/* RFGPO14_PAD */
#define RFGPO14_PAD_MODE(i)				MUX_VALUE(10, 28, (i))
#define MP_RFGPO14_PAD_RF_SPI2_DIN		RFGPO14_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO14_PAD_A2B_DAT12		RFGPO14_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO14_PAD_TA_STROBE14		RFGPO14_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO14_PAD_GPIO46			RFGPO14_PAD_MODE(IOMUX_MODE_4)

/* RFGPO15_PAD */
#define RFGPO15_PAD_MODE(i)				MUX_VALUE(11, 0, (i))
#define MP_RFGPO15_PAD_RF_SPI2_CS		RFGPO15_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO15_PAD_A2B_DAT13		RFGPO15_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO15_PAD_TA_STROBE15		RFGPO15_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO15_PAD_GPIO47			RFGPO15_PAD_MODE(IOMUX_MODE_4)

/* RFGPO16_PAD */
#define RFGPO16_PAD_MODE(i)				MUX_VALUE(11, 4, (i))
#define MP_RFGPO16_PAD_RF_SPI2_CLK		RFGPO16_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO16_PAD_A2B_DAT14		RFGPO16_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO16_PAD_TA_STROBE16		RFGPO16_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO16_PAD_GPIO48			RFGPO16_PAD_MODE(IOMUX_MODE_4)

/* RFGPO17_PAD */
#define RFGPO17_PAD_MODE(i)				MUX_VALUE(11, 8, (i))
#define MP_RFGPO17_PAD_RF_SPI6_CS		RFGPO17_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO17_PAD_A2B_DAT15		RFGPO17_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO17_PAD_TA_STROBE17		RFGPO17_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO17_PAD_GPIO49			RFGPO17_PAD_MODE(IOMUX_MODE_4)

/* RFGPO18_PAD */
#define RFGPO18_PAD_MODE(i)				MUX_VALUE(11, 12, (i))
#define MP_RFGPO18_PAD_TX_FRAMESYNC		RFGPO18_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO18_PAD_A2B_DAT16		RFGPO18_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO18_PAD_TA_STROBE18		RFGPO18_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO18_PAD_GPIO50			RFGPO18_PAD_MODE(IOMUX_MODE_4)

/* RFGPO19_PAD */
#define RFGPO19_PAD_MODE(i)				MUX_VALUE(11, 16, (i))
#define MP_RFGPO19_PAD_RX_FRAMESYNC		RFGPO19_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO19_PAD_A2B_DAT17		RFGPO19_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO19_PAD_TA_STROBE19		RFGPO19_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO19_PAD_GPIO51			RFGPO19_PAD_MODE(IOMUX_MODE_4)

/* RFGPO1_PAD */
#define RFGPO1_PAD_MODE(i)				MUX_VALUE(11, 20, (i))
#define MP_RFGPO1_PAD_RF_SPI4_DIN		RFGPO1_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO1_PAD_A2B_WLD			RFGPO1_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO1_PAD_TA_STROBE1		RFGPO1_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO1_PAD_GPIO33			RFGPO1_PAD_MODE(IOMUX_MODE_4)

/* RFGPO20_PAD */
#define RFGPO20_PAD_MODE(i)				MUX_VALUE(11, 24, (i))
#define MP_RFGPO20_PAD_DAC_CLK			RFGPO20_PAD_MODE(IOMUX_MODE_0)
#define MP_RFGPO20_PAD_ET_DATACLK		RFGPO20_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO20_PAD_B2A_CLK			RFGPO20_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO20_PAD_TA_STROBE20		RFGPO20_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO20_PAD_TA_GPIO52		RFGPO20_PAD_MODE(IOMUX_MODE_4)

/* RFGPO21_PAD */
#define RFGPO21_PAD_MODE(i)				MUX_VALUE(11, 28, (i))
#define MP_RFGPO21_PAD_DAC_IO00			RFGPO21_PAD_MODE(IOMUX_MODE_0)
#define MP_RFGPO21_PAD_RF_SPI3_DIO		RFGPO21_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO21_PAD_B2A_RST			RFGPO21_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO21_PAD_TA_STROBE21		RFGPO21_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO21_PAD_TA_GPIO53		RFGPO21_PAD_MODE(IOMUX_MODE_4)

/* RFGPO22_PAD */
#define RFGPO22_PAD_MODE(i)				MUX_VALUE(12, 0, (i))
#define MP_RFGPO22_PAD_DAC_IO01			RFGPO22_PAD_MODE(IOMUX_MODE_0)
#define MP_RFGPO22_PAD_RF_SPI3_DIN		RFGPO22_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO22_PAD_B2A_DAT00		RFGPO22_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO22_PAD_TA_STROBE22		RFGPO22_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO22_PAD_TA_GPIO54		RFGPO22_PAD_MODE(IOMUX_MODE_4)

/* RFGPO23_PAD */
#define RFGPO23_PAD_MODE(i)				MUX_VALUE(12, 4, (i))
#define MP_RFGPO23_PAD_DAC_IO02			RFGPO23_PAD_MODE(IOMUX_MODE_0)
#define MP_RFGPO23_PAD_RF_SPI3_CS		RFGPO23_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO23_PAD_B2A_DAT01		RFGPO23_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO23_PAD_TA_STROBE23		RFGPO23_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO23_PAD_TA_GPIO55		RFGPO23_PAD_MODE(IOMUX_MODE_4)

/* RFGPO24_PAD */
#define RFGPO24_PAD_MODE(i)				MUX_VALUE(12, 8, (i))
#define MP_RFGPO24_PAD_DAC_IO03			RFGPO24_PAD_MODE(IOMUX_MODE_0)
#define MP_RFGPO24_PAD_RF_SPI3_CLK		RFGPO24_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO24_PAD_B2A_DAT02		RFGPO24_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO24_PAD_TA_STROBE24		RFGPO24_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO24_PAD_TA_GPIO56		RFGPO24_PAD_MODE(IOMUX_MODE_4)


/* RFGPO2_PAD */
#define RFGPO2_PAD_MODE(i)				MUX_VALUE(12, 12, (i))
#define MP_RFGPO2_PAD_RF_SPI4_CS		RFGPO2_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO2_PAD_A2B_DAT00			RFGPO2_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO2_PAD_TA_STROBE2		RFGPO2_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO2_PAD_GPIO34			RFGPO2_PAD_MODE(IOMUX_MODE_4)

/* RFGPO3_PAD */
#define RFGPO3_PAD_MODE(i)				MUX_VALUE(12, 16, (i))
#define MP_RFGPO3_PAD_RF_SPI4_CLK		RFGPO3_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO3_PAD_A2B_DAT01			RFGPO3_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO3_PAD_TA_STROBE3		RFGPO3_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO3_PAD_GPIO35			RFGPO3_PAD_MODE(IOMUX_MODE_4)

/* RFGPO4_PAD */
#define RFGPO4_PAD_MODE(i)				MUX_VALUE(12, 20, (i))
#define MP_RFGPO4_PAD_RF_SPI5_DIO		RFGPO4_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO4_PAD_A2B_DAT02			RFGPO4_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO4_PAD_TA_STROBE4		RFGPO4_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO4_PAD_GPIO36			RFGPO4_PAD_MODE(IOMUX_MODE_4)

/* RFGPO5_PAD */
#define RFGPO5_PAD_MODE(i)				MUX_VALUE(12, 24, (i))
#define MP_RFGPO5_PAD_RF_SPI5_DIN		RFGPO5_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO5_PAD_A2B_DAT03			RFGPO5_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO5_PAD_TA_STROBE5		RFGPO5_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO5_PAD_GPIO37			RFGPO5_PAD_MODE(IOMUX_MODE_4)

/* RFGPO6_PAD */
#define RFGPO6_PAD_MODE(i)				MUX_VALUE(12, 28, (i))
#define MP_RFGPO6_PAD_RF_SPI5_CS		RFGPO6_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO6_PAD_A2B_DAT04			RFGPO6_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO6_PAD_TA_STROBE6		RFGPO6_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO6_PAD_GPIO38			RFGPO6_PAD_MODE(IOMUX_MODE_4)


/* RFGPO7_PAD */
#define RFGPO7_PAD_MODE(i)				MUX_VALUE(13, 0, (i))
#define MP_RFGPO7_PAD_RF_SPI5_CLK		RFGPO7_PAD_MODE(IOMUX_MODE_1)
#define MP_RFGPO7_PAD_A2B_DAT05			RFGPO7_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO7_PAD_TA_STROBE7		RFGPO7_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO7_PAD_GPIO39			RFGPO7_PAD_MODE(IOMUX_MODE_4)

/* RFGPO8_PAD */
#define RFGPO8_PAD_MODE(i)				MUX_VALUE(13, 4, (i))
#define MP_RFGPO8_PAD_A2B_DAT06			RFGPO8_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO8_PAD_TA_STROBE8		RFGPO8_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO8_PAD_GPIO40			RFGPO8_PAD_MODE(IOMUX_MODE_4)

/* RFGPO9_PAD */
#define RFGPO9_PAD_MODE(i)				MUX_VALUE(13, 8, (i))
#define MP_RFGPO9_PAD_A2B_DAT07			RFGPO9_PAD_MODE(IOMUX_MODE_2)
#define MP_RFGPO9_PAD_TA_STROBE9		RFGPO9_PAD_MODE(IOMUX_MODE_3)
#define MP_RFGPO9_PAD_GPIO41			RFGPO9_PAD_MODE(IOMUX_MODE_4)

/* SPI0CLK_PAD */
#define SPI0CLK_PAD_MODE(i)				MUX_VALUE(13, 12, (i))
#define MP_SPI0CLK_PAD_DAC_IO07			SPI0CLK_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI0CLK_PAD_RF_SPI0_CLK		SPI0CLK_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI0CLK_PAD_B2A_DAT06		SPI0CLK_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI0CLK_PAD_TA_STROBE28		SPI0CLK_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI0CLK_PAD_GPIO60			SPI0CLK_PAD_MODE(IOMUX_MODE_4)

/* SPI0CS_PAD */
#define SPI0CS_PAD_MODE(i)				MUX_VALUE(13, 16, (i))
#define MP_SPI0CS_PAD_DAC_IO06			SPI0CS_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI0CS_PAD_RF_SPI0_CS		SPI0CS_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI0CS_PAD_B2A_DAT05			SPI0CS_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI0CS_PAD_TA_STROBE27		SPI0CS_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI0CS_PAD_GPIO59			SPI0CS_PAD_MODE(IOMUX_MODE_4)

/* SPI0DIN_PAD */
#define SPI0DIN_PAD_MODE(i)				MUX_VALUE(13, 20, (i))
#define MP_SPI0DIN_PAD_DAC_IO05			SPI0DIN_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI0DIN_PAD_RF_SPI0_DIN		SPI0DIN_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI0DIN_PAD_B2A_DAT04		SPI0DIN_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI0DIN_PAD_TA_STROBE26		SPI0DIN_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI0DIN_PAD_GPIO58			SPI0DIN_PAD_MODE(IOMUX_MODE_4)

/* SPI0DIO_PAD */
#define SPI0DIO_PAD_MODE(i)				MUX_VALUE(13, 24, (i))
#define MP_SPI0DIO_PAD_DAC_IO04			SPI0DIO_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI0DIO_PAD_RF_SPI0_DIO		SPI0DIO_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI0DIO_PAD_B2A_DAT03		SPI0DIO_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI0DIO_PAD_TA_STROBE25		SPI0DIO_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI0DIO_PAD_GPIO57			SPI0DIO_PAD_MODE(IOMUX_MODE_4)

/* SPI1CLK_PAD */
#define SPI1CLK_PAD_MODE(i)				MUX_VALUE(13, 28, (i))
#define MP_SPI1CLK_PAD_DAC_IO11			SPI1CLK_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI1CLK_PAD_RF_SPI1_CLK		SPI1CLK_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI1CLK_PAD_B3A_DAT10		SPI1CLK_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI1CLK_PAD_TA_STROBE32		SPI1CLK_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI1CLK_PAD_GPIO64			SPI1CLK_PAD_MODE(IOMUX_MODE_4)


/* SPI1CS_PAD */
#define SPI1CS_PAD_MODE(i)				MUX_VALUE(14, 0, (i))
#define MP_SPI1CS_PAD_DAC_IO10			SPI1CS_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI1CS_PAD_RF_SPI1_CS		SPI1CS_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI1CS_PAD_B3A_DAT09			SPI1CS_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI1CS_PAD_TA_STROBE31		SPI1CS_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI1CS_PAD_GPIO63			SPI1CS_PAD_MODE(IOMUX_MODE_4)

/* SPI1DIN_PAD */
#define SPI1DIN_PAD_MODE(i)				MUX_VALUE(14, 4, (i))
#define MP_SPI1DIN_PAD_DAC_IO09			SPI1DIN_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI1DIN_PAD_RF_SPI1_DIN		SPI1DIN_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI1DIN_PAD_B3A_DAT08		SPI1DIN_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI1DIN_PAD_TA_STROBE30		SPI1DIN_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI1DIN_PAD_GPIO62			SPI1DIN_PAD_MODE(IOMUX_MODE_4)

/* SPI1DIO_PAD */
#define SPI1DIO_PAD_MODE(i)				MUX_VALUE(14, 8, (i))
#define MP_SPI1DIO_PAD_DAC_IO08			SPI1DIO_PAD_MODE(IOMUX_MODE_0)
#define MP_SPI1DIO_PAD_RF_SPI1_DIO		SPI1DIO_PAD_MODE(IOMUX_MODE_1)
#define MP_SPI1DIO_PAD_B3A_DAT07		SPI1DIO_PAD_MODE(IOMUX_MODE_2)
#define MP_SPI1DIO_PAD_TA_STROBE29		SPI1DIO_PAD_MODE(IOMUX_MODE_3)
#define MP_SPI1DIO_PAD_GPIO61			SPI1DIO_PAD_MODE(IOMUX_MODE_4)


/* SDCLK_PAD */
#define SDCLK_PAD_MODE(i)				MUX_VALUE(14, 12, (i))
#define MP_SDCLK_PAD_SDS_CLK			SDCLK_PAD_MODE(IOMUX_MODE_0)
#define MP_SDCLK_PAD_SDM1_CLK			SDCLK_PAD_MODE(IOMUX_MODE_1)
#define MP_SDCLK_PAD_SPIM1_CS			SDCLK_PAD_MODE(IOMUX_MODE_2)
#define MP_SDCLK_PAD_GPIO95				SDCLK_PAD_MODE(IOMUX_MODE_4)

/* SDCMD_PAD */
#define SDCMD_PAD_MODE(i)				MUX_VALUE(14, 16, (i))
#define MP_SDCMD_PAD_SDS_CMD			SDCMD_PAD_MODE(IOMUX_MODE_0)
#define MP_SDCMD_PAD_SDM1_CMD			SDCMD_PAD_MODE(IOMUX_MODE_1)
#define MP_SDCMD_PAD_SPIM1_CLK			SDCMD_PAD_MODE(IOMUX_MODE_2)
#define MP_SDCMD_PAD_GPIO96				SDCMD_PAD_MODE(IOMUX_MODE_4)

/* SDDAT0_PAD */
#define SDDAT0_PAD_MODE(i)				MUX_VALUE(14, 20, (i))
#define MP_SDDAT0_PAD_SDS_DAT0			SDDAT0_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT0_PAD_SDM1_DAT0			SDDAT0_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT0_PAD_SPIM1_MISO		SDDAT0_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT0_PAD_GPIO97			SDDAT0_PAD_MODE(IOMUX_MODE_4)

/* SDDAT1_PAD */
#define SDDAT1_PAD_MODE(i)				MUX_VALUE(14, 24, (i))
#define MP_SDDAT1_PAD_SDS_DAT1			SDDAT1_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT1_PAD_SDM1_DAT1			SDDAT1_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT1_PAD_SPIM1_MOSI		SDDAT1_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT1_PAD_GPIO98			SDDAT1_PAD_MODE(IOMUX_MODE_4)


/* SDDAT2_PAD */
#define SDDAT2_PAD_MODE(i)				MUX_VALUE(15, 0, (i))
#define MP_SDDAT2_PAD_SDS_DAT2			SDDAT2_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT2_PAD_SDM1_DAT2			SDDAT2_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT2_PAD_SPIM1_CS2			SDDAT2_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT2_PAD_GPIO99			SDDAT2_PAD_MODE(IOMUX_MODE_4)

/* SDDAT3_PAD */
#define SDDAT3_PAD_MODE(i)				MUX_VALUE(15, 4, (i))
#define MP_SDDAT3_PAD_SDS_DAT3			SDDAT3_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT3_PAD_SDM1_DAT3			SDDAT3_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT3_PAD_B2A_DAT42			SDDAT3_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT3_PAD_GPIO100			SDDAT3_PAD_MODE(IOMUX_MODE_4)

/* SDDAT4_PAD */
#define SDDAT4_PAD_MODE(i)				MUX_VALUE(15, 8, (i))
#define MP_SDDAT4_PAD_SDS_DAT4			SDDAT4_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT4_PAD_ETH_TX_D0			SDDAT4_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT4_PAD_B2A_DAT38			SDDAT4_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT4_PAD_GPIO101			SDDAT4_PAD_MODE(IOMUX_MODE_4)

/* SDDAT5_PAD */
#define SDDAT5_PAD_MODE(i)				MUX_VALUE(15, 12, (i))
#define MP_SDDAT5_PAD_SDS_DAT5			SDDAT5_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT5_PAD_ETH_TX_D1			SDDAT5_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT5_PAD_B2A_DAT39			SDDAT5_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT5_PAD_GPIO102			SDDAT5_PAD_MODE(IOMUX_MODE_4)

/* SDDAT6_PAD */
#define SDDAT6_PAD_MODE(i)				MUX_VALUE(15, 16, (i))
#define MP_SDDAT6_PAD_SDS_DAT6			SDDAT6_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT6_PAD_ETH_TX_D2			SDDAT6_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT6_PAD_B2A_DAT40			SDDAT6_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT6_PAD_GPIO103			SDDAT6_PAD_MODE(IOMUX_MODE_4)

/* SDDAT7_PAD */
#define SDDAT7_PAD_MODE(i)				MUX_VALUE(15, 20, (i))
#define MP_SDDAT7_PAD_SDS_DAT7			SDDAT7_PAD_MODE(IOMUX_MODE_0)
#define MP_SDDAT7_PAD_ETH_TX_D3			SDDAT7_PAD_MODE(IOMUX_MODE_1)
#define MP_SDDAT7_PAD_B2A_DAT41			SDDAT7_PAD_MODE(IOMUX_MODE_2)
#define MP_SDDAT7_PAD_GPIO104			SDDAT7_PAD_MODE(IOMUX_MODE_4)

/* SIMCLK_PAD */
#define SIMCLK_PAD_MODE(i)				MUX_VALUE(15, 24, (i))
#define MP_SIMCLK_PAD_SIM_CLK			SIMCLK_PAD_MODE(IOMUX_MODE_0)
#define MP_SIMCLK_PAD_TESTPIN9			SIMCLK_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMCLK_PAD_GPIO18			SIMCLK_PAD_MODE(IOMUX_MODE_4)

/* SIMIO_PAD */
#define SIMIO_PAD_MODE(i)				MUX_VALUE(15, 28, (i))
#define MP_SIMIO_PAD_SIM_IO				SIMIO_PAD_MODE(IOMUX_MODE_0)
#define MP_SIMIO_PAD_TESTPIN8			SIMIO_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMIO_PAD_GPIO17				SIMIO_PAD_MODE(IOMUX_MODE_4)

/* SIMRST_PAD */
#define SIMRST_PAD_MODE(i)				MUX_VALUE(16, 0, (i))
#define MP_SIMRST_PAD_SIM_RST			SIMRST_PAD_MODE(IOMUX_MODE_0)
#define MP_SIMRST_PAD_TESTPIN7			SIMRST_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMRST_PAD_GPIO16			SIMRST_PAD_MODE(IOMUX_MODE_4)

/* SIMSTOPN_PAD */
#define SIMSTOPN_PAD_MODE(i)			MUX_VALUE(16, 4, (i))
#define MP_SIMSTOPN_PAD_TESTPIN11		SIMSTOPN_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMSTOPN_PAD_GPIO20			SIMSTOPN_PAD_MODE(IOMUX_MODE_4)

/* SIMSVL_CLK_PAD */
#define SIMSLVCLK_PAD_MODE(i)			MUX_VALUE(16, 8, (i))
#define MP_SIMSLVCLK_PAD_SIMSLV_CLK		SIMSLVCLK_PAD_MODE(IOMUX_MODE_0)
#define MP_SIMSLVCLK_PAD_IICM2_SCL		SIMSLVCLK_PAD_MODE(IOMUX_MODE_1)
#define MP_SIMSLVCLK_PAD_UART1_TX		SIMSLVCLK_PAD_MODE(IOMUX_MODE_2)
#define MP_SIMSLVCLK_PAD_TESTPIN14		SIMSLVCLK_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMSLVCLK_PAD_GPIO14			SIMSLVCLK_PAD_MODE(IOMUX_MODE_4)

/* SIMSVL_DAT_PAD */
#define SIMSLVDAT_PAD_MODE(i)			MUX_VALUE(16, 12, (i))
#define MP_SIMSLVDAT_PAD_SIMSLV_DAT		SIMSLVDAT_PAD_MODE(IOMUX_MODE_0)
#define MP_SIMSLVDAT_PAD_IICM2_SDA		SIMSLVDAT_PAD_MODE(IOMUX_MODE_1)
#define MP_SIMSLVDAT_PAD_UART1_RX		SIMSLVDAT_PAD_MODE(IOMUX_MODE_2)
#define MP_SIMSLVDAT_PAD_TESTPIN15		SIMSLVDAT_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMSLVDAT_PAD_GPIO15			SIMSLVDAT_PAD_MODE(IOMUX_MODE_4)

/* SIMSVL_VDET_PAD */
#define SIMSLVVDET_PAD_MODE(i)			MUX_VALUE(16, 16, (i))
#define MP_SIMSLVVDET_PAD_TESTPIN12		SIMSLVVDET_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMSLVVDET_PAD_GPIO12		SIMSLVVDET_PAD_MODE(IOMUX_MODE_4)

/* SIMSVL_RST_PAD */
#define SIMSLVRST_PAD_MODE(i)			MUX_VALUE(16, 20, (i))
#define MP_SIMSLVRST_PAD_SIMSLV_RST		SIMSLVRST_PAD_MODE(IOMUX_MODE_0)
#define MP_SIMSLVRST_PAD_TESTPIN13		SIMSLVRST_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMSLVRST_PAD_GPIO13			SIMSLVRST_PAD_MODE(IOMUX_MODE_4)

/* TCXO_ON_PAD */
#define TCXO_ON_PAD_MODE(i)				MUX_VALUE(16, 24, (i))
#define MP_TCXO_ON_PAD_TCXO_ON			TCXO_ON_PAD_MODE(IOMUX_MODE_0)
#define MP_TCXO_ON_PAD_GPIO21			TCXO_ON_PAD_MODE(IOMUX_MODE_4)

/* TCXO_OFF_PAD */
#define TCXO_OFF_PAD_MODE(i)			MUX_VALUE(16, 28, (i))
#define MP_TCXO_OFF_PAD_TCXO_OFF		TCXO_OFF_PAD_MODE(IOMUX_MODE_0)
#define MP_TCXO_OFF_PAD_GPIO22			TCXO_OFF_PAD_MODE(IOMUX_MODE_4)


/* USBCLK_PAD */
#define USBCLK_PAD_MODE(i)				MUX_VALUE(17, 0, (i))
#define MP_USBCLK_PAD_USB_CLK			USBCLK_PAD_MODE(IOMUX_MODE_0)
#define MP_USBCLK_PAD_ETH_RX_D1			USBCLK_PAD_MODE(IOMUX_MODE_1)
#define MP_USBCLK_PAD_SIM2_CLK			USBCLK_PAD_MODE(IOMUX_MODE_2)
#define MP_USBCLK_PAD_GPIO138			USBCLK_PAD_MODE(IOMUX_MODE_4)

/* USBDAT0_PAD */
#define USBDAT0_PAD_MODE(i)				MUX_VALUE(17, 4, (i))
#define MP_USBDAT0_PAD_USB_D0			USBDAT0_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT0_PAD_ETH_MDC			USBDAT0_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT0_PAD_GPIO144			USBDAT0_PAD_MODE(IOMUX_MODE_4)

/* USBDAT1_PAD */
#define USBDAT1_PAD_MODE(i)				MUX_VALUE(17, 8, (i))
#define MP_USBDAT1_PAD_USB_D1			USBDAT1_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT1_PAD_ETH_MDIO			USBDAT1_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT1_PAD_GPIO131			USBDAT1_PAD_MODE(IOMUX_MODE_4)

/* USBDAT2_PAD */
#define USBDAT2_PAD_MODE(i)				MUX_VALUE(17, 12, (i))
#define MP_USBDAT2_PAD_USB_D2			USBDAT2_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT2_PAD_ETH_CRS			USBDAT2_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT2_PAD_GPIO132			USBDAT2_PAD_MODE(IOMUX_MODE_4)

/* USBDAT3_PAD */
#define USBDAT3_PAD_MODE(i)				MUX_VALUE(17, 16, (i))
#define MP_USBDAT3_PAD_USB_D3			USBDAT3_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT3_PAD_ETH_COL			USBDAT3_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT3_PAD_GPIO133			USBDAT3_PAD_MODE(IOMUX_MODE_4)

/* USBDAT4_PAD */
#define USBDAT4_PAD_MODE(i)				MUX_VALUE(17, 20, (i))
#define MP_USBDAT4_PAD_USB_D4			USBDAT4_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT4_PAD_ETH_RX_DV		USBDAT4_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT4_PAD_GPIO134			USBDAT4_PAD_MODE(IOMUX_MODE_4)

/* USBDAT5_PAD */
#define USBDAT5_PAD_MODE(i)				MUX_VALUE(17, 24, (i))
#define MP_USBDAT5_PAD_USB_D5			USBDAT5_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT5_PAD_ETH_RX_ER		USBDAT5_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT5_PAD_GPIO135			USBDAT5_PAD_MODE(IOMUX_MODE_4)

/* USBDAT6_PAD */
#define USBDAT6_PAD_MODE(i)				MUX_VALUE(17, 28, (i))
#define MP_USBDAT6_PAD_USB_D6			USBDAT6_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT6_PAD_ETH_RX_CLK		USBDAT6_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT6_PAD_GPIO136			USBDAT6_PAD_MODE(IOMUX_MODE_4)


/* USBDAT7_PAD */
#define USBDAT7_PAD_MODE(i)				MUX_VALUE(18, 0, (i))
#define MP_USBDAT7_PAD_USB_D7			USBDAT7_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDAT7_PAD_ETH_RX_D0		USBDAT7_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDAT7_PAD_GPIO137			USBDAT7_PAD_MODE(IOMUX_MODE_4)

/* USBDIR_PAD */
#define USBDIR_PAD_MODE(i)				MUX_VALUE(18, 4, (i))
#define MP_USBDIR_PAD_USB_DIR			USBDIR_PAD_MODE(IOMUX_MODE_0)
#define MP_USBDIR_PAD_ETH_RX_D2			USBDIR_PAD_MODE(IOMUX_MODE_1)
#define MP_USBDIR_PAD_SDM2_CMD			USBDIR_PAD_MODE(IOMUX_MODE_2)
#define MP_USBDIR_PAD_GPIO139			USBDIR_PAD_MODE(IOMUX_MODE_4)

/* USBNXT_PAD */
#define USBNXT_PAD_MODE(i)				MUX_VALUE(18, 8, (i))
#define MP_USBNXT_PAD_USB_NXT			USBNXT_PAD_MODE(IOMUX_MODE_0)
#define MP_USBNXT_PAD_ETH_RX_D3			USBNXT_PAD_MODE(IOMUX_MODE_1)
#define MP_USBNXT_PAD_SDM2_DAT0			USBNXT_PAD_MODE(IOMUX_MODE_2)
#define MP_USBNXT_PAD_GPIO140			USBNXT_PAD_MODE(IOMUX_MODE_4)

/* USBSTP_PAD */
#define USBSTP_PAD_MODE(i)				MUX_VALUE(18, 12, (i))
#define MP_USBSTP_PAD_USB_STP			USBSTP_PAD_MODE(IOMUX_MODE_0)
#define MP_USBSTP_PAD_ETH_TX_EN			USBSTP_PAD_MODE(IOMUX_MODE_1)
#define MP_USBSTP_PAD_SDM2_DAT1			USBSTP_PAD_MODE(IOMUX_MODE_2)
#define MP_USBSTP_PAD_GPIO141			USBSTP_PAD_MODE(IOMUX_MODE_4)

/* USBPHYRSTN_PAD */
#define USBPHYRSTN_PAD_MODE(i)			MUX_VALUE(18, 16, (i))
#define MP_USBPHYRSTN_PAD_USBPHY_RSTN	USBPHYRSTN_PAD_MODE(IOMUX_MODE_0)
#define MP_USBPHYRSTN_PAD_ETH_TX_ER		USBPHYRSTN_PAD_MODE(IOMUX_MODE_1)
#define MP_USBPHYRSTN_PAD_SDM2_DAT2		USBPHYRSTN_PAD_MODE(IOMUX_MODE_2)
#define MP_USBPHYRSTN_PAD_GPIO142		USBPHYRSTN_PAD_MODE(IOMUX_MODE_4)

/* CLKOUT_PAD */
#define CLKOUT_PAD_MODE(i)				MUX_VALUE(18, 20, (i))
#define MP_CLKOUT_PAD_CLKOUT			CLKOUT_PAD_MODE(IOMUX_MODE_0)
#define MP_CLKOUT_PAD_ETH_TX_CLK		CLKOUT_PAD_MODE(IOMUX_MODE_1)
#define MP_CLKOUT_PAD_SDM2_DAT3			CLKOUT_PAD_MODE(IOMUX_MODE_2)
#define MP_CLKOUT_PAD_GPIO143			CLKOUT_PAD_MODE(IOMUX_MODE_4)

/* GPIO152_PAD */
#define GPIO152_PAD_MODE(i)				MUX_VALUE(18, 24, (i))
#define MP_GPIO152_PAD_EXTWAKEUP_INTN2	GPIO152_PAD_MODE(IOMUX_MODE_0)

/* SIM_MODE_PAD */
#define SIMMODE_PAD_MODE(i)				MUX_VALUE(18, 28, (i))
#define MP_SIMMODE_PAD_TESTPIN10		SIMMODE_PAD_MODE(IOMUX_MODE_3)
#define MP_SIMMODE_PAD_GPIO19			SIMMODE_PAD_MODE(IOMUX_MODE_4)


typedef unsigned long p4a_mux_pin_t;
    
extern void p4a_iomux_config(p4a_mux_pin_t pins[], int num);

#endif	/* _P4A_IOMUX_H */
